@regionName = 서울
@categoryId = 1

### GET Categories Data
GET https://eatgo-customer-api.ahastudio.com/categories

### GET Regions Data
GET https://eatgo-customer-api.ahastudio.com/regions

### GET Restaurants Data
GET https://eatgo-customer-api.ahastudio.com/restaurants?region={{regionName}}&category={{categoryId}}